application: rsantoniphphello
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /index\.html
  script: main.php

- url: /
  script: main.php

- url: /maps
  script: maps.php

- url: /.*
  script: not_found.php
